[project]
name = "beets-quicktag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beets>=2.3.0",
    "just-playback>=0.1.8",
    "textual>=3.2.0",
]

[dependency-groups]
dev = [
    "debugpy>=1.8.14",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
    "ruff>=0.11.9",
    "textual-dev>=1.7.0",
]

[tool.uv.sources]
beets = { git = "https://github.com/beetbox/beets.git" }
